'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'zh' | 'ja';

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
}

export const languages: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'zh', name: 'Chinese', nativeName: '中文' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語' },
];

interface Translations {
  [key: string]: {
    [lang in Language]: string;
  };
}

const translations: Translations = {
  // Header
  'header.search.placeholder': {
    en: 'Search Amazon',
    es: 'Buscar en Amazon',
    fr: 'Rechercher sur Amazon',
    de: 'Amazon durchsuchen',
    it: 'Cerca su Amazon',
    pt: 'Pesquisar na Amazon',
    zh: '搜索亚马逊',
    ja: 'Amazonを検索',
  },
  'header.all': {
    en: 'All',
    es: 'Todos',
    fr: 'Tout',
    de: 'Alle',
    it: 'Tutti',
    pt: 'Todos',
    zh: '全部',
    ja: 'すべて',
  },
  'header.hello': {
    en: "You're signed in",
    es: 'Has iniciado sesión',
    fr: 'Vous êtes connecté',
    de: 'Sie sind angemeldet',
    it: 'Hai effettuato l\'accesso',
    pt: 'Você está conectado',
    zh: '您已登录',
    ja: 'ログインしています',
  },
  'header.hello.guest': {
    en: 'Hello, sign in',
    es: 'Hola, inicia sesión',
    fr: 'Bonjour, connectez-vous',
    de: 'Hallo, anmelden',
    it: 'Ciao, accedi',
    pt: 'Olá, faça login',
    zh: '你好，登录',
    ja: 'こんにちは、ログイン',
  },
  'header.account': {
    en: 'Account & Lists',
    es: 'Cuenta y Listas',
    fr: 'Compte et listes',
    de: 'Konto und Listen',
    it: 'Account ed elenchi',
    pt: 'Conta e Listas',
    zh: '账户和列表',
    ja: 'アカウントとリスト',
  },
  'header.returns': {
    en: 'Returns',
    es: 'Devoluciones',
    fr: 'Retours',
    de: 'Rückgaben',
    it: 'Resi',
    pt: 'Devoluções',
    zh: '退货',
    ja: '返品',
  },
  'header.orders': {
    en: '& Orders',
    es: 'y Pedidos',
    fr: 'et commandes',
    de: 'und Bestellungen',
    it: 'e Ordini',
    pt: 'e Pedidos',
    zh: '和订单',
    ja: 'と注文',
  },
  'header.changeLanguage': {
    en: 'Change Language',
    es: 'Cambiar idioma',
    fr: 'Changer de langue',
    de: 'Sprache ändern',
    it: 'Cambia lingua',
    pt: 'Alterar idioma',
    zh: '更改语言',
    ja: '言語を変更',
  },
  'header.signedIn': {
    en: 'You\'re signed in',
    es: 'Has iniciado sesión',
    fr: 'Vous êtes connecté',
    de: 'Sie sind angemeldet',
    it: 'Hai effettuato l\'accesso',
    pt: 'Você está conectado',
    zh: '您已登录',
    ja: 'ログインしています',
  },
  'header.newCustomer': {
    en: 'New customer?',
    es: '¿Nuevo cliente?',
    fr: 'Nouveau client?',
    de: 'Neuer Kunde?',
    it: 'Nuovo cliente?',
    pt: 'Novo cliente?',
    zh: '新客户？',
    ja: '新規のお客様ですか？',
  },
  'header.startHere': {
    en: 'Start here.',
    es: 'Comienza aquí.',
    fr: 'Commencez ici.',
    de: 'Hier beginnen.',
    it: 'Inizia qui.',
    pt: 'Comece aqui.',
    zh: '从这里开始。',
    ja: 'ここから始めましょう。',
  },
  'header.quickLinks': {
    en: 'Quick Links',
    es: 'Enlaces rápidos',
    fr: 'Liens rapides',
    de: 'Schnelllinks',
    it: 'Link rapidi',
    pt: 'Links rápidos',
    zh: '快速链接',
    ja: 'クイックリンク',
  },
  'header.shopByDepartment': {
    en: 'Shop by Department',
    es: 'Comprar por departamento',
    fr: 'Acheter par département',
    de: 'Nach Abteilung einkaufen',
    it: 'Acquista per reparto',
    pt: 'Comprar por departamento',
    zh: '按部门购物',
    ja: '部門別に購入',
  },
  'header.cart': {
    en: 'Cart',
    es: 'Carrito',
    fr: 'Panier',
    de: 'Warenkorb',
    it: 'Carrello',
    pt: 'Carrinho',
    zh: '购物车',
    ja: 'カート',
  },
  'header.delivering': {
    en: 'Delivering to',
    es: 'Entregar a',
    fr: 'Livrer à',
    de: 'Liefern an',
    it: 'Consegna a',
    pt: 'Entregar em',
    zh: '配送到',
    ja: '配達先',
  },
  // Navigation
  'nav.all': {
    en: 'All',
    es: 'Todo',
    fr: 'Tout',
    de: 'Alle',
    it: 'Tutti',
    pt: 'Todos',
    zh: '全部',
    ja: 'すべて',
  },
  'nav.amazonHaul': {
    en: 'Amazon Haul',
    es: 'Compras de Amazon',
    fr: 'Achats Amazon',
    de: 'Amazon-Einkäufe',
    it: 'Acquisti Amazon',
    pt: 'Compras na Amazon',
    zh: 'Amazon采购',
    ja: 'Amazonの買い物',
  },
  'nav.medicalCare': {
    en: 'Medical Care',
    es: 'Atención Médica',
    fr: 'Soins médicaux',
    de: 'Medizinische Versorgung',
    it: 'Assistenza medica',
    pt: 'Cuidados Médicos',
    zh: '医疗护理',
    ja: '医療ケア',
  },
  'nav.amazonBasics': {
    en: 'Amazon Basics',
    es: 'Amazon Basics',
    fr: 'Amazon Basics',
    de: 'Amazon Basics',
    it: 'Amazon Basics',
    pt: 'Amazon Basics',
    zh: 'Amazon基础款',
    ja: 'Amazon Basics',
  },
  'nav.bestSellers': {
    en: 'Best Sellers',
    es: 'Más Vendidos',
    fr: 'Meilleures ventes',
    de: 'Bestseller',
    it: 'I più venduti',
    pt: 'Mais Vendidos',
    zh: '畅销商品',
    ja: 'ベストセラー',
  },
  'nav.books': {
    en: 'Books',
    es: 'Libros',
    fr: 'Livres',
    de: 'Bücher',
    it: 'Libri',
    pt: 'Livros',
    zh: '图书',
    ja: '本',
  },
  'nav.registry': {
    en: 'Registry',
    es: 'Registro',
    fr: 'Registre',
    de: 'Registrierung',
    it: 'Registro',
    pt: 'Lista de Presentes',
    zh: '注册表',
    ja: 'レジストリ',
  },
  'nav.newReleases': {
    en: 'New Releases',
    es: 'Novedades',
    fr: 'Nouveautés',
    de: 'Neuerscheinungen',
    it: 'Nuove uscite',
    pt: 'Lançamentos',
    zh: '新品上市',
    ja: '新作',
  },
  'nav.giftCards': {
    en: 'Gift Cards',
    es: 'Tarjetas Regalo',
    fr: 'Cartes cadeaux',
    de: 'Geschenkkarten',
    it: 'Carte regalo',
    pt: 'Cartões Presente',
    zh: '礼品卡',
    ja: 'ギフトカード',
  },
  'nav.smartHome': {
    en: 'Smart Home',
    es: 'Hogar Inteligente',
    fr: 'Maison connectée',
    de: 'Smart Home',
    it: 'Casa intelligente',
    pt: 'Casa Inteligente',
    zh: '智能家居',
    ja: 'スマートホーム',
  },
  'nav.todaysDeals': {
    en: 'Today\'s Deals',
    es: 'Ofertas del Día',
    fr: 'Offres du jour',
    de: 'Angebote des Tages',
    it: 'Offerte del giorno',
    pt: 'Ofertas do Dia',
    zh: '今日特价',
    ja: '今日のお得情報',
  },
  // Common
  'common.addToCart': {
    en: 'Add to Cart',
    es: 'Añadir al carrito',
    fr: 'Ajouter au panier',
    de: 'In den Warenkorb',
    it: 'Aggiungi al carrello',
    pt: 'Adicionar ao carrinho',
    zh: '添加到购物车',
    ja: 'カートに追加',
  },
  'common.buyNow': {
    en: 'Buy Now',
    es: 'Comprar ahora',
    fr: 'Acheter maintenant',
    de: 'Jetzt kaufen',
    it: 'Acquista ora',
    pt: 'Comprar agora',
    zh: '立即购买',
    ja: '今すぐ購入',
  },
  'common.signIn': {
    en: 'Sign in',
    es: 'Iniciar sesión',
    fr: 'Se connecter',
    de: 'Anmelden',
    it: 'Accedi',
    pt: 'Entrar',
    zh: '登录',
    ja: 'ログイン',
  },
  'common.signOut': {
    en: 'Sign Out',
    es: 'Cerrar sesión',
    fr: 'Se déconnecter',
    de: 'Abmelden',
    it: 'Esci',
    pt: 'Sair',
    zh: '退出',
    ja: 'ログアウト',
  },
  'cart.empty': {
    en: 'Your Amazon Cart is empty',
    es: 'Tu carrito de Amazon está vacío',
    fr: 'Votre panier Amazon est vide',
    de: 'Ihr Amazon-Warenkorb ist leer',
    it: 'Il tuo carrello Amazon è vuoto',
    pt: 'Seu carrinho da Amazon está vazio',
    zh: '您的亚马逊购物车是空的',
    ja: 'Amazonカートは空です',
  },
  'cart.shopDeals': {
    en: 'Shop today\'s deals',
    es: 'Comprar ofertas de hoy',
    fr: 'Acheter les offres du jour',
    de: 'Angebote des Tages ansehen',
    it: 'Acquista offerte di oggi',
    pt: 'Comprar ofertas de hoje',
    zh: '购买今日特价',
    ja: '今日のお得情報を見る',
  },
  'cart.title': {
    en: 'Shopping Cart',
    es: 'Carrito de compras',
    fr: 'Panier d\'achat',
    de: 'Warenkorb',
    it: 'Carrello della spesa',
    pt: 'Carrinho de compras',
    zh: '购物车',
    ja: 'ショッピングカート',
  },
  'cart.subtotal': {
    en: 'Subtotal',
    es: 'Subtotal',
    fr: 'Sous-total',
    de: 'Zwischensumme',
    it: 'Subtotale',
    pt: 'Subtotal',
    zh: '小计',
    ja: '小計',
  },
  'cart.items': {
    en: 'items',
    es: 'artículos',
    fr: 'articles',
    de: 'Artikel',
    it: 'articoli',
    pt: 'itens',
    zh: '件商品',
    ja: 'アイテム',
  },
  'cart.checkout': {
    en: 'Proceed to Checkout',
    es: 'Proceder al pago',
    fr: 'Passer à la caisse',
    de: 'Zur Kasse gehen',
    it: 'Procedi al checkout',
    pt: 'Fazer checkout',
    zh: '去结算',
    ja: 'チェックアウトに進む',
  },
  'cart.added': {
    en: 'Added to cart!',
    es: '¡Añadido al carrito!',
    fr: 'Ajouté au panier!',
    de: 'Zum Warenkorb hinzugefügt!',
    it: 'Aggiunto al carrello!',
    pt: 'Adicionado ao carrinho!',
    zh: '已添加到购物车！',
    ja: 'カートに追加されました！',
  },
  // Wishlist
  'wishlist.add': {
    en: 'Add to Wish List',
    es: 'Añadir a la lista de deseos',
    fr: 'Ajouter à la liste de souhaits',
    de: 'Zur Wunschliste hinzufügen',
    it: 'Aggiungi alla lista dei desideri',
    pt: 'Adicionar à lista de desejos',
    zh: '添加到心愿单',
    ja: 'ほしい物リストに追加',
  },
  'wishlist.remove': {
    en: 'Remove from Wish List',
    es: 'Eliminar de la lista de deseos',
    fr: 'Retirer de la liste de souhaits',
    de: 'Von Wunschliste entfernen',
    it: 'Rimuovi dalla lista dei desideri',
    pt: 'Remover da lista de desejos',
    zh: '从心愿单移除',
    ja: 'ほしい物リストから削除',
  },
  // Homepage
  'home.prime.title': {
    en: 'Fast, free shipping plus streaming',
    es: 'Envío rápido y gratis más transmisión',
    fr: 'Livraison rapide et gratuite plus streaming',
    de: 'Schneller, kostenloser Versand plus Streaming',
    it: 'Spedizione veloce e gratuita più streaming',
    pt: 'Envio rápido e gratuíto mais streaming',
    zh: '快速免费配送加流媒体',
    ja: '高速無料配送とストリーミング',
  },
  'home.prime.button': {
    en: 'Join Prime',
    es: 'Únete a Prime',
    fr: 'Rejoindre Prime',
    de: 'Prime beitreten',
    it: 'Unisciti a Prime',
    pt: 'Assinar Prime',
    zh: '加入Prime',
    ja: 'Primeに加入',
  },
  'home.bestSellers': {
    en: 'Best Sellers in Computers & Accessories',
    es: 'Más Vendidos en Computadoras y Accesorios',
    fr: 'Meilleures ventes en ordinateurs et accessoires',
    de: 'Bestseller in Computern & Zubehör',
    it: 'I più venduti in Computer e Accessori',
    pt: 'Mais Vendidos em Computadores e Acessórios',
    zh: '计算机和配件畅销商品',
    ja: 'コンピューターとアクセサリーのベストセラー',
  },
  // Product Page
  'product.back': {
    en: '← Back to results',
    es: '← Volver a resultados',
    fr: '← Retour aux résultats',
    de: '← Zurück zu Ergebnissen',
    it: '← Torna ai risultati',
    pt: '← Voltar aos resultados',
    zh: '← 返回结果',
    ja: '← 結果に戻る',
  },
  'product.tags': {
    en: 'Tags:',
    es: 'Etiquetas:',
    fr: 'Tags:',
    de: 'Tags:',
    it: 'Tag:',
    pt: 'Tags:',
    zh: '标签：',
    ja: 'タグ：',
  },
  'product.description': {
    en: 'Description',
    es: 'Descripción',
    fr: 'Description',
    de: 'Beschreibung',
    it: 'Descrizione',
    pt: 'Descrição',
    zh: '描述',
    ja: '説明',
  },
  'product.quantity': {
    en: 'Quantity:',
    es: 'Cantidad:',
    fr: 'Quantité:',
    de: 'Menge:',
    it: 'Quantità:',
    pt: 'Quantidade:',
    zh: '数量：',
    ja: '数量：',
  },
  'product.shipsFrom': {
    en: 'Ships from:',
    es: 'Enviado desde:',
    fr: 'Expédié depuis:',
    de: 'Versand von:',
    it: 'Spedito da:',
    pt: 'Enviado de:',
    zh: '发货地：',
    ja: '発送元：',
  },
  'product.soldBy': {
    en: 'Sold by:',
    es: 'Vendido por:',
    fr: 'Vendu par:',
    de: 'Verkauft von:',
    it: 'Venduto da:',
    pt: 'Vendido por:',
    zh: '销售方：',
    ja: '販売者：',
  },
  'product.returnPolicy': {
    en: 'Return policy:',
    es: 'Política de devolución:',
    fr: 'Politique de retour:',
    de: 'Rückgaberecht:',
    it: 'Politica di reso:',
    pt: 'Política de devolução:',
    zh: '退货政策：',
    ja: '返品ポリシー：',
  },
  'product.returnEligible': {
    en: 'Eligible for Return, Refund or Replacement',
    es: 'Elegible para devolución, reembolso o reemplazo',
    fr: 'Éligible au retour, remboursement ou remplacement',
    de: 'Berechtigt für Rückgabe, Erstattung oder Ersatz',
    it: 'Eligibile per reso, rimborso o sostituzione',
    pt: 'Elegível para devolução, reembolso ou substituição',
    zh: '符合退货、退款或换货条件',
    ja: '返品、返金、交換の対象',
  },
  'product.related': {
    en: 'Customers who viewed this item also viewed',
    es: 'Los clientes que vieron este artículo también vieron',
    fr: 'Les clients qui ont consulté cet article ont également consulté',
    de: 'Kunden, die diesen Artikel angesehen haben, haben auch angesehen',
    it: 'I clienti che hanno visualizzato questo articolo hanno anche visualizzato',
    pt: 'Clientes que visualizaram este item também visualizaram',
    zh: '查看此商品的客户还查看了',
    ja: 'この商品を見たお客様はこちらも見ています',
  },
  // Search
  'search.title': {
    en: 'Search results for',
    es: 'Resultados de búsqueda para',
    fr: 'Résultats de recherche pour',
    de: 'Suchergebnisse für',
    it: 'Risultati di ricerca per',
    pt: 'Resultados da pesquisa para',
    zh: '搜索结果',
    ja: '検索結果',
  },
  'search.noResults': {
    en: 'No products found',
    es: 'No se encontraron productos',
    fr: 'Aucun produit trouvé',
    de: 'Keine Produkte gefunden',
    it: 'Nessun prodotto trovato',
    pt: 'Nenhum produto encontrado',
    zh: '未找到商品',
    ja: '商品が見つかりません',
  },
  'search.tryAdjusting': {
    en: 'Try adjusting your search terms or browse our categories',
    es: 'Intenta ajustar tus términos de búsqueda o navega por nuestras categorías',
    fr: 'Essayez d\'ajuster vos termes de recherche ou parcourez nos catégories',
    de: 'Versuchen Sie, Ihre Suchbegriffe anzupassen oder durchsuchen Sie unsere Kategorien',
    it: 'Prova ad aggiustare i tuoi termini di ricerca o sfoglia le nostre categorie',
    pt: 'Tente ajustar seus termos de pesquisa ou navegue por nossas categorias',
    zh: '尝试调整搜索词或浏览我们的类别',
    ja: '検索語を調整するか、カテゴリを閲覧してください',
  },
  'search.continueShopping': {
    en: 'Continue Shopping',
    es: 'Continuar comprando',
    fr: 'Continuer les achats',
    de: 'Einkaufen fortsetzen',
    it: 'Continua lo shopping',
    pt: 'Continuar comprando',
    zh: '继续购物',
    ja: 'ショッピングを続ける',
  },
  'search.results': {
    en: 'results found',
    es: 'resultados encontrados',
    fr: 'résultats trouvés',
    de: 'Ergebnisse gefunden',
    it: 'risultati trovati',
    pt: 'resultados encontrados',
    zh: '个结果',
    ja: '件の結果',
  },
  'search.result': {
    en: 'result found',
    es: 'resultado encontrado',
    fr: 'résultat trouvé',
    de: 'Ergebnis gefunden',
    it: 'risultato trovato',
    pt: 'resultado encontrado',
    zh: '个结果',
    ja: '件の結果',
  },
  // Category
  'category.products': {
    en: 'products found',
    es: 'productos encontrados',
    fr: 'produits trouvés',
    de: 'Produkte gefunden',
    it: 'prodotti trovati',
    pt: 'produtos encontrados',
    zh: '个商品',
    ja: '件の商品',
  },
  'category.product': {
    en: 'product found',
    es: 'producto encontrado',
    fr: 'produit trouvé',
    de: 'Produkt gefunden',
    it: 'prodotto trovato',
    pt: 'produto encontrado',
    zh: '个商品',
    ja: '件の商品',
  },
  'category.noProducts': {
    en: 'No products in this category',
    es: 'No hay productos en esta categoría',
    fr: 'Aucun produit dans cette catégorie',
    de: 'Keine Produkte in dieser Kategorie',
    it: 'Nessun prodotto in questa categoria',
    pt: 'Nenhum produto nesta categoria',
    zh: '此类别中没有商品',
    ja: 'このカテゴリに商品はありません',
  },
  // Login
  'login.title': {
    en: 'Sign in',
    es: 'Iniciar sesión',
    fr: 'Se connecter',
    de: 'Anmelden',
    it: 'Accedi',
    pt: 'Entrar',
    zh: '登录',
    ja: 'ログイン',
  },
  'login.email': {
    en: 'Email or mobile phone number',
    es: 'Correo electrónico o número de teléfono móvil',
    fr: 'E-mail ou numéro de téléphone portable',
    de: 'E-Mail oder Handynummer',
    it: 'Email o numero di telefono cellulare',
    pt: 'E-mail ou número de telefone celular',
    zh: '电子邮件或手机号码',
    ja: 'メールアドレスまたは携帯電話番号',
  },
  'login.password': {
    en: 'Password',
    es: 'Contraseña',
    fr: 'Mot de passe',
    de: 'Passwort',
    it: 'Password',
    pt: 'Senha',
    zh: '密码',
    ja: 'パスワード',
  },
  'login.signingIn': {
    en: 'Signing in...',
    es: 'Iniciando sesión...',
    fr: 'Connexion...',
    de: 'Anmeldung...',
    it: 'Accesso in corso...',
    pt: 'Entrando...',
    zh: '登录中...',
    ja: 'ログイン中...',
  },
  'login.agree': {
    en: 'By continuing, you agree to Amazon\'s',
    es: 'Al continuar, aceptas las',
    fr: 'En continuant, vous acceptez les',
    de: 'Durch Fortfahren stimmen Sie den',
    it: 'Continuando, accetti le',
    pt: 'Ao continuar, você concorda com as',
    zh: '继续即表示您同意亚马逊的',
    ja: '続行することで、Amazonの',
  },
  'login.conditions': {
    en: 'Conditions of Use',
    es: 'Condiciones de Uso',
    fr: 'Conditions d\'utilisation',
    de: 'Nutzungsbedingungen',
    it: 'Condizioni d\'uso',
    pt: 'Condições de Uso',
    zh: '使用条件',
    ja: '利用規約',
  },
  'login.privacy': {
    en: 'Privacy Notice',
    es: 'Aviso de Privacidad',
    fr: 'Avis de confidentialité',
    de: 'Datenschutzerklärung',
    it: 'Informativa sulla privacy',
    pt: 'Aviso de Privacidade',
    zh: '隐私声明',
    ja: 'プライバシー規約',
  },
  'login.newCustomer': {
    en: 'New to Amazon?',
    es: '¿Nuevo en Amazon?',
    fr: 'Nouveau sur Amazon?',
    de: 'Neu bei Amazon?',
    it: 'Nuovo su Amazon?',
    pt: 'Novo na Amazon?',
    zh: '新用户？',
    ja: 'Amazon初めてですか？',
  },
  'login.createAccount': {
    en: 'Create your Amazon account',
    es: 'Crea tu cuenta de Amazon',
    fr: 'Créez votre compte Amazon',
    de: 'Erstellen Sie Ihr Amazon-Konto',
    it: 'Crea il tuo account Amazon',
    pt: 'Crie sua conta Amazon',
    zh: '创建您的亚马逊账户',
    ja: 'Amazonアカウントを作成',
  },
  'login.testAccount': {
    en: 'Test Account Credentials',
    es: 'Credenciales de Cuenta de Prueba',
    fr: 'Identifiants du compte de test',
    de: 'Testkontodaten',
    it: 'Credenziali Account di Test',
    pt: 'Credenciais da Conta de Teste',
    zh: '测试账户凭据',
    ja: 'テストアカウントの認証情報',
  },
  'login.fillCredentials': {
    en: 'Fill Credentials',
    es: 'Llenar Credenciales',
    fr: 'Remplir les identifiants',
    de: 'Anmeldedaten ausfüllen',
    it: 'Compila Credenziali',
    pt: 'Preencher Credenciais',
    zh: '填写凭据',
    ja: '認証情報を入力',
  },
  // Register
  'register.title': {
    en: 'Create account',
    es: 'Crear cuenta',
    fr: 'Créer un compte',
    de: 'Konto erstellen',
    it: 'Crea account',
    pt: 'Criar conta',
    zh: '创建账户',
    ja: 'アカウントを作成',
  },
  'register.name': {
    en: 'Your name',
    es: 'Tu nombre',
    fr: 'Votre nom',
    de: 'Ihr Name',
    it: 'Il tuo nome',
    pt: 'Seu nome',
    zh: '您的姓名',
    ja: 'お名前',
  },
  'register.passwordHint': {
    en: 'Passwords must be at least 6 characters.',
    es: 'Las contraseñas deben tener al menos 6 caracteres.',
    fr: 'Les mots de passe doivent contenir au moins 6 caractères.',
    de: 'Passwörter müssen mindestens 6 Zeichen lang sein.',
    it: 'Le password devono contenere almeno 6 caratteri.',
    pt: 'As senhas devem ter pelo menos 6 caracteres.',
    zh: '密码必须至少6个字符。',
    ja: 'パスワードは6文字以上である必要があります。',
  },
  'register.reenterPassword': {
    en: 'Re-enter password',
    es: 'Vuelve a ingresar la contraseña',
    fr: 'Retaper le mot de passe',
    de: 'Passwort erneut eingeben',
    it: 'Reinserisci la password',
    pt: 'Digite a senha novamente',
    zh: '重新输入密码',
    ja: 'パスワードを再入力',
  },
  'register.creating': {
    en: 'Creating account...',
    es: 'Creando cuenta...',
    fr: 'Création du compte...',
    de: 'Konto wird erstellt...',
    it: 'Creazione account...',
    pt: 'Criando conta...',
    zh: '正在创建账户...',
    ja: 'アカウントを作成中...',
  },
  'register.createButton': {
    en: 'Create your Amazon account',
    es: 'Crea tu cuenta de Amazon',
    fr: 'Créez votre compte Amazon',
    de: 'Erstellen Sie Ihr Amazon-Konto',
    it: 'Crea il tuo account Amazon',
    pt: 'Crie sua conta Amazon',
    zh: '创建您的亚马逊账户',
    ja: 'Amazonアカウントを作成',
  },
  'register.alreadyHave': {
    en: 'Already have an account?',
    es: '¿Ya tienes una cuenta?',
    fr: 'Vous avez déjà un compte?',
    de: 'Haben Sie bereits ein Konto?',
    it: 'Hai già un account?',
    pt: 'Já tem uma conta?',
    zh: '已有账户？',
    ja: 'すでにアカウントをお持ちですか？',
  },
  // Account Pages
  'account.orders': {
    en: 'Your Orders',
    es: 'Tus Pedidos',
    fr: 'Vos commandes',
    de: 'Ihre Bestellungen',
    it: 'I tuoi ordini',
    pt: 'Seus Pedidos',
    zh: '您的订单',
    ja: '注文履歴',
  },
  'account.yourOrders': {
    en: 'Your Orders',
    es: 'Tus Pedidos',
    fr: 'Vos commandes',
    de: 'Ihre Bestellungen',
    it: 'I tuoi ordini',
    pt: 'Seus Pedidos',
    zh: '您的订单',
    ja: '注文履歴',
  },
  'account.orders.empty': {
    en: 'You haven\'t placed any orders yet',
    es: 'Aún no has realizado ningún pedido',
    fr: 'Vous n\'avez pas encore passé de commande',
    de: 'Sie haben noch keine Bestellungen aufgegeben',
    it: 'Non hai ancora effettuato ordini',
    pt: 'Você ainda não fez nenhum pedido',
    zh: '您还没有下过任何订单',
    ja: 'まだ注文がありません',
  },
  'account.orders.startShopping': {
    en: 'Start Shopping',
    es: 'Comenzar a comprar',
    fr: 'Commencer les achats',
    de: 'Einkaufen beginnen',
    it: 'Inizia lo shopping',
    pt: 'Começar a comprar',
    zh: '开始购物',
    ja: 'ショッピングを始める',
  },
  'account.orders.orderPlaced': {
    en: 'Order placed',
    es: 'Pedido realizado',
    fr: 'Commande passée',
    de: 'Bestellung aufgegeben',
    it: 'Ordine effettuato',
    pt: 'Pedido realizado',
    zh: '下单日期',
    ja: '注文日',
  },
  'account.orders.total': {
    en: 'Total',
    es: 'Total',
    fr: 'Total',
    de: 'Gesamt',
    it: 'Totale',
    pt: 'Total',
    zh: '总计',
    ja: '合計',
  },
  'account.orders.order': {
    en: 'Order',
    es: 'Pedido',
    fr: 'Commande',
    de: 'Bestellung',
    it: 'Ordine',
    pt: 'Pedido',
    zh: '订单',
    ja: '注文',
  },
  'account.orders.buyAgain': {
    en: 'Buy Again',
    es: 'Comprar de nuevo',
    fr: 'Acheter à nouveau',
    de: 'Erneut kaufen',
    it: 'Acquista di nuovo',
    pt: 'Comprar novamente',
    zh: '再次购买',
    ja: 'もう一度購入',
  },
  'account.orders.trackPackage': {
    en: 'Track Package',
    es: 'Rastrear paquete',
    fr: 'Suivre le colis',
    de: 'Paket verfolgen',
    it: 'Traccia pacco',
    pt: 'Rastrear pacote',
    zh: '跟踪包裹',
    ja: 'パッケージを追跡',
  },
  'account.wishlist': {
    en: 'Your Wish List',
    es: 'Tu Lista de Deseos',
    fr: 'Votre liste de souhaits',
    de: 'Ihre Wunschliste',
    it: 'La tua lista dei desideri',
    pt: 'Sua Lista de Desejos',
    zh: '您的愿望清单',
    ja: 'ほしい物リスト',
  },
  'account.wishlist.empty': {
    en: 'Your wish list is empty',
    es: 'Tu lista de deseos está vacía',
    fr: 'Votre liste de souhaits est vide',
    de: 'Ihre Wunschliste ist leer',
    it: 'La tua lista dei desideri è vuota',
    pt: 'Sua lista de desejos está vazia',
    zh: '您的愿望清单是空的',
    ja: 'ほしい物リストは空です',
  },
  'account.wishlist.startAdding': {
    en: 'Start adding items you want to save for later',
    es: 'Comienza a agregar artículos que quieras guardar para después',
    fr: 'Commencez à ajouter des articles que vous souhaitez enregistrer pour plus tard',
    de: 'Beginnen Sie, Artikel hinzuzufügen, die Sie für später speichern möchten',
    it: 'Inizia ad aggiungere articoli che vuoi salvare per dopo',
    pt: 'Comece a adicionar itens que deseja salvar para depois',
    zh: '开始添加您想稍后保存的商品',
    ja: '後で保存したいアイテムを追加し始めましょう',
  },
  'account.wishlist.items': {
    en: 'items in your wish list',
    es: 'artículos en tu lista de deseos',
    fr: 'articles dans votre liste de souhaits',
    de: 'Artikel auf Ihrer Wunschliste',
    it: 'articoli nella tua lista dei desideri',
    pt: 'itens na sua lista de desejos',
    zh: '件商品在您的愿望清单中',
    ja: '件のアイテムがほしい物リストにあります',
  },
  'account.wishlist.item': {
    en: 'item in your wish list',
    es: 'artículo en tu lista de deseos',
    fr: 'article dans votre liste de souhaits',
    de: 'Artikel auf Ihrer Wunschliste',
    it: 'articolo nella tua lista dei desideri',
    pt: 'item na sua lista de desejos',
    zh: '件商品在您的愿望清单中',
    ja: '件のアイテムがほしい物リストにあります',
  },
  'account.wishlist.remove': {
    en: 'Remove from List',
    es: 'Eliminar de la lista',
    fr: 'Retirer de la liste',
    de: 'Aus Liste entfernen',
    it: 'Rimuovi dalla lista',
    pt: 'Remover da lista',
    zh: '从列表中移除',
    ja: 'リストから削除',
  },
  'account.title': {
    en: 'Your Account',
    es: 'Tu Cuenta',
    fr: 'Votre compte',
    de: 'Ihr Konto',
    it: 'Il tuo account',
    pt: 'Sua Conta',
    zh: '您的账户',
    ja: 'アカウント',
  },
  'account.yourAccount': {
    en: 'Your Account',
    es: 'Tu Cuenta',
    fr: 'Votre compte',
    de: 'Ihr Konto',
    it: 'Il tuo account',
    pt: 'Sua Conta',
    zh: '您的账户',
    ja: 'アカウント',
  },
  'account.needSignIn': {
    en: 'You need to be signed in to view your account',
    es: 'Necesitas iniciar sesión para ver tu cuenta',
    fr: 'Vous devez être connecté pour voir votre compte',
    de: 'Sie müssen angemeldet sein, um Ihr Konto anzuzeigen',
    it: 'Devi essere connesso per visualizzare il tuo account',
    pt: 'Você precisa estar conectado para ver sua conta',
    zh: '您需要登录才能查看您的账户',
    ja: 'アカウントを表示するにはログインが必要です',
  },
  'account.settings': {
    en: 'Account Settings',
    es: 'Configuración de Cuenta',
    fr: 'Paramètres du compte',
    de: 'Kontoeinstellungen',
    it: 'Impostazioni account',
    pt: 'Configurações da Conta',
    zh: '账户设置',
    ja: 'アカウント設定',
  },
  'account.personalInfo': {
    en: 'Personal Information',
    es: 'Información Personal',
    fr: 'Informations personnelles',
    de: 'Persönliche Informationen',
    it: 'Informazioni personali',
    pt: 'Informações Pessoais',
    zh: '个人信息',
    ja: '個人情報',
  },
  'account.edit': {
    en: 'Edit',
    es: 'Editar',
    fr: 'Modifier',
    de: 'Bearbeiten',
    it: 'Modifica',
    pt: 'Editar',
    zh: '编辑',
    ja: '編集',
  },
  'account.phone': {
    en: 'Phone Number',
    es: 'Número de teléfono',
    fr: 'Numéro de téléphone',
    de: 'Telefonnummer',
    it: 'Numero di telefono',
    pt: 'Número de telefone',
    zh: '电话号码',
    ja: '電話番号',
  },
  'account.notProvided': {
    en: 'Not provided',
    es: 'No proporcionado',
    fr: 'Non fourni',
    de: 'Nicht angegeben',
    it: 'Non fornito',
    pt: 'Não fornecido',
    zh: '未提供',
    ja: '提供されていません',
  },
  'account.saveChanges': {
    en: 'Save Changes',
    es: 'Guardar cambios',
    fr: 'Enregistrer les modifications',
    de: 'Änderungen speichern',
    it: 'Salva modifiche',
    pt: 'Salvar alterações',
    zh: '保存更改',
    ja: '変更を保存',
  },
  'account.cancel': {
    en: 'Cancel',
    es: 'Cancelar',
    fr: 'Annuler',
    de: 'Abbrechen',
    it: 'Annulla',
    pt: 'Cancelar',
    zh: '取消',
    ja: 'キャンセル',
  },
  'account.addressBook': {
    en: 'Address Book',
    es: 'Libreta de Direcciones',
    fr: 'Carnet d\'adresses',
    de: 'Adressbuch',
    it: 'Rubrica',
    pt: 'Livro de Endereços',
    zh: '地址簿',
    ja: 'アドレス帳',
  },
  'account.addNewAddress': {
    en: 'Add New Address',
    es: 'Agregar Nueva Dirección',
    fr: 'Ajouter une nouvelle adresse',
    de: 'Neue Adresse hinzufügen',
    it: 'Aggiungi nuovo indirizzo',
    pt: 'Adicionar Novo Endereço',
    zh: '添加新地址',
    ja: '新しい住所を追加',
  },
  'account.defaultAddress': {
    en: 'Default Address',
    es: 'Dirección Predeterminada',
    fr: 'Adresse par défaut',
    de: 'Standardadresse',
    it: 'Indirizzo predefinito',
    pt: 'Endereço Padrão',
    zh: '默认地址',
    ja: 'デフォルト住所',
  },
  'account.noAddresses': {
    en: 'No addresses saved. Add an address for faster checkout.',
    es: 'No hay direcciones guardadas. Agrega una dirección para un pago más rápido.',
    fr: 'Aucune adresse enregistrée. Ajoutez une adresse pour un paiement plus rapide.',
    de: 'Keine Adressen gespeichert. Fügen Sie eine Adresse für einen schnelleren Checkout hinzu.',
    it: 'Nessun indirizzo salvato. Aggiungi un indirizzo per un checkout più veloce.',
    pt: 'Nenhum endereço salvo. Adicione um endereço para checkout mais rápido.',
    zh: '未保存地址。添加地址以加快结账。',
    ja: '保存された住所はありません。より速いチェックアウトのために住所を追加してください。',
  },
  'account.paymentMethods': {
    en: 'Payment Methods',
    es: 'Métodos de Pago',
    fr: 'Moyens de paiement',
    de: 'Zahlungsmethoden',
    it: 'Metodi di pagamento',
    pt: 'Métodos de Pagamento',
    zh: '付款方式',
    ja: '支払い方法',
  },
  'account.addPaymentMethod': {
    en: 'Add Payment Method',
    es: 'Agregar Método de Pago',
    fr: 'Ajouter un moyen de paiement',
    de: 'Zahlungsmethode hinzufügen',
    it: 'Aggiungi metodo di pagamento',
    pt: 'Adicionar Método de Pagamento',
    zh: '添加付款方式',
    ja: '支払い方法を追加',
  },
  'account.noPaymentMethods': {
    en: 'No payment methods saved. Add a payment method for faster checkout.',
    es: 'No hay métodos de pago guardados. Agrega un método de pago para un pago más rápido.',
    fr: 'Aucun moyen de paiement enregistré. Ajoutez un moyen de paiement pour un paiement plus rapide.',
    de: 'Keine Zahlungsmethoden gespeichert. Fügen Sie eine Zahlungsmethode für einen schnelleren Checkout hinzu.',
    it: 'Nessun metodo di pagamento salvato. Aggiungi un metodo di pagamento per un checkout più veloce.',
    pt: 'Nenhum método de pagamento salvo. Adicione um método de pagamento para checkout mais rápido.',
    zh: '未保存付款方式。添加付款方式以加快结账。',
    ja: '保存された支払い方法はありません。より速いチェックアウトのために支払い方法を追加してください。',
  },
  'account.primeMembership': {
    en: 'Prime Membership',
    es: 'Membresía Prime',
    fr: 'Abonnement Prime',
    de: 'Prime-Mitgliedschaft',
    it: 'Abbonamento Prime',
    pt: 'Assinatura Prime',
    zh: 'Prime会员',
    ja: 'Primeメンバーシップ',
  },
  'account.notPrime': {
    en: 'Not a Prime member?',
    es: '¿No eres miembro Prime?',
    fr: 'Pas membre Prime?',
    de: 'Kein Prime-Mitglied?',
    it: 'Non sei membro Prime?',
    pt: 'Não é membro Prime?',
    zh: '不是Prime会员？',
    ja: 'Primeメンバーではありませんか？',
  },
  'account.joinPrimeDesc': {
    en: 'Join Prime to enjoy free shipping, streaming, and exclusive deals.',
    es: 'Únete a Prime para disfrutar de envío gratis, transmisión y ofertas exclusivas.',
    fr: 'Rejoignez Prime pour profiter de la livraison gratuite, du streaming et d\'offres exclusives.',
    de: 'Werden Sie Prime-Mitglied und genießen Sie kostenlosen Versand, Streaming und exklusive Angebote.',
    it: 'Unisciti a Prime per godere di spedizione gratuita, streaming e offerte esclusive.',
    pt: 'Assine o Prime para aproveitar frete grátis, streaming e ofertas exclusivas.',
    zh: '加入Prime享受免费配送、流媒体和独家优惠。',
    ja: 'Primeに加入して、無料配送、ストリーミング、限定オファーをお楽しみください。',
  },
  'account.recommendations': {
    en: 'Your Recommendations',
    es: 'Tus Recomendaciones',
    fr: 'Vos recommandations',
    de: 'Ihre Empfehlungen',
    it: 'Le tue raccomandazioni',
    pt: 'Suas Recomendações',
    zh: '您的推荐',
    ja: 'おすすめ',
  },
  'account.recommendations.desc': {
    en: 'Based on your browsing history and preferences, here are some products we think you\'ll love.',
    es: 'Basado en tu historial de navegación y preferencias, aquí hay algunos productos que creemos que te encantarán.',
    fr: 'Basé sur votre historique de navigation et vos préférences, voici quelques produits que nous pensons que vous aimerez.',
    de: 'Basierend auf Ihrem Browsing-Verlauf und Ihren Präferenzen finden Sie hier einige Produkte, von denen wir denken, dass Sie sie lieben werden.',
    it: 'Basato sulla tua cronologia di navigazione e preferenze, ecco alcuni prodotti che pensiamo ti piaceranno.',
    pt: 'Com base no seu histórico de navegação e preferências, aqui estão alguns produtos que achamos que você vai adorar.',
    zh: '根据您的浏览历史和偏好，以下是我们认为您会喜欢的商品。',
    ja: '閲覧履歴と好みに基づいて、お気に入りになると思われる商品をご紹介します。',
  },
  // Checkout
  'checkout.title': {
    en: 'Checkout',
    es: 'Pago',
    fr: 'Paiement',
    de: 'Kasse',
    it: 'Checkout',
    pt: 'Checkout',
    zh: '结账',
    ja: 'チェックアウト',
  },
  'checkout.shipping': {
    en: 'Shipping',
    es: 'Envío',
    fr: 'Livraison',
    de: 'Versand',
    it: 'Spedizione',
    pt: 'Envio',
    zh: '配送',
    ja: '配送',
  },
  'checkout.payment': {
    en: 'Payment',
    es: 'Pago',
    fr: 'Paiement',
    de: 'Zahlung',
    it: 'Pagamento',
    pt: 'Pagamento',
    zh: '付款',
    ja: '支払い',
  },
  'checkout.review': {
    en: 'Review',
    es: 'Revisar',
    fr: 'Révision',
    de: 'Überprüfung',
    it: 'Revisione',
    pt: 'Revisão',
    zh: '审核',
    ja: '確認',
  },
  'checkout.shippingAddress': {
    en: 'Shipping Address',
    es: 'Dirección de Envío',
    fr: 'Adresse de livraison',
    de: 'Lieferadresse',
    it: 'Indirizzo di spedizione',
    pt: 'Endereço de Envio',
    zh: '配送地址',
    ja: '配送先住所',
  },
  'checkout.fullName': {
    en: 'Full Name',
    es: 'Nombre completo',
    fr: 'Nom complet',
    de: 'Vollständiger Name',
    it: 'Nome completo',
    pt: 'Nome completo',
    zh: '全名',
    ja: '氏名',
  },
  'checkout.address': {
    en: 'Address',
    es: 'Dirección',
    fr: 'Adresse',
    de: 'Adresse',
    it: 'Indirizzo',
    pt: 'Endereço',
    zh: '地址',
    ja: '住所',
  },
  'checkout.city': {
    en: 'City',
    es: 'Ciudad',
    fr: 'Ville',
    de: 'Stadt',
    it: 'Città',
    pt: 'Cidade',
    zh: '城市',
    ja: '都市',
  },
  'checkout.state': {
    en: 'State',
    es: 'Estado',
    fr: 'État',
    de: 'Bundesland',
    it: 'Stato',
    pt: 'Estado',
    zh: '州/省',
    ja: '都道府県',
  },
  'checkout.zipCode': {
    en: 'ZIP Code',
    es: 'Código postal',
    fr: 'Code postal',
    de: 'Postleitzahl',
    it: 'Codice postale',
    pt: 'CEP',
    zh: '邮政编码',
    ja: '郵便番号',
  },
  'checkout.phone': {
    en: 'Phone Number',
    es: 'Número de teléfono',
    fr: 'Numéro de téléphone',
    de: 'Telefonnummer',
    it: 'Numero di telefono',
    pt: 'Número de telefone',
    zh: '电话号码',
    ja: '電話番号',
  },
  'checkout.continuePayment': {
    en: 'Continue to Payment',
    es: 'Continuar al pago',
    fr: 'Continuer vers le paiement',
    de: 'Zur Zahlung fortfahren',
    it: 'Continua al pagamento',
    pt: 'Continuar para o pagamento',
    zh: '继续付款',
    ja: '支払いに進む',
  },
  'checkout.paymentMethod': {
    en: 'Payment Method',
    es: 'Método de Pago',
    fr: 'Moyen de paiement',
    de: 'Zahlungsmethode',
    it: 'Metodo di pagamento',
    pt: 'Método de Pagamento',
    zh: '付款方式',
    ja: '支払い方法',
  },
  'checkout.cardNumber': {
    en: 'Card Number',
    es: 'Número de tarjeta',
    fr: 'Numéro de carte',
    de: 'Kartennummer',
    it: 'Numero di carta',
    pt: 'Número do cartão',
    zh: '卡号',
    ja: 'カード番号',
  },
  'checkout.cardName': {
    en: 'Name on Card',
    es: 'Nombre en la tarjeta',
    fr: 'Nom sur la carte',
    de: 'Name auf der Karte',
    it: 'Nome sulla carta',
    pt: 'Nome no cartão',
    zh: '持卡人姓名',
    ja: 'カード名義人',
  },
  'checkout.expiryDate': {
    en: 'Expiry Date',
    es: 'Fecha de vencimiento',
    fr: 'Date d\'expiration',
    de: 'Ablaufdatum',
    it: 'Data di scadenza',
    pt: 'Data de validade',
    zh: '有效期',
    ja: '有効期限',
  },
  'checkout.cvv': {
    en: 'CVV',
    es: 'CVV',
    fr: 'CVV',
    de: 'CVV',
    it: 'CVV',
    pt: 'CVV',
    zh: 'CVV',
    ja: 'CVV',
  },
  'checkout.useFakeCard': {
    en: 'Use any fake card number (e.g., 4111 1111 1111 1111)',
    es: 'Usa cualquier número de tarjeta falso (ej., 4111 1111 1111 1111)',
    fr: 'Utilisez n\'importe quel numéro de carte factice (par ex., 4111 1111 1111 1111)',
    de: 'Verwenden Sie eine beliebige gefälschte Kartennummer (z. B. 4111 1111 1111 1111)',
    it: 'Usa qualsiasi numero di carta falso (es., 4111 1111 1111 1111)',
    pt: 'Use qualquer número de cartão falso (ex., 4111 1111 1111 1111)',
    zh: '使用任何假卡号（例如，4111 1111 1111 1111）',
    ja: '任意の偽のカード番号を使用（例：4111 1111 1111 1111）',
  },
  'checkout.back': {
    en: 'Back',
    es: 'Atrás',
    fr: 'Retour',
    de: 'Zurück',
    it: 'Indietro',
    pt: 'Voltar',
    zh: '返回',
    ja: '戻る',
  },
  'checkout.continueReview': {
    en: 'Continue to Review',
    es: 'Continuar a revisar',
    fr: 'Continuer vers la révision',
    de: 'Zur Überprüfung fortfahren',
    it: 'Continua alla revisione',
    pt: 'Continuar para revisão',
    zh: '继续审核',
    ja: '確認に進む',
  },
  'checkout.reviewOrder': {
    en: 'Review Your Order',
    es: 'Revisa tu pedido',
    fr: 'Réviser votre commande',
    de: 'Ihre Bestellung überprüfen',
    it: 'Rivedi il tuo ordine',
    pt: 'Revise seu pedido',
    zh: '审核您的订单',
    ja: '注文を確認',
  },
  'checkout.shippingAddressLabel': {
    en: 'Shipping Address',
    es: 'Dirección de Envío',
    fr: 'Adresse de livraison',
    de: 'Lieferadresse',
    it: 'Indirizzo di spedizione',
    pt: 'Endereço de Envío',
    zh: '配送地址',
    ja: '配送先住所',
  },
  'checkout.paymentMethodLabel': {
    en: 'Payment Method',
    es: 'Método de Pago',
    fr: 'Moyen de paiement',
    de: 'Zahlungsmethode',
    it: 'Metodo di pagamento',
    pt: 'Método de Pagamento',
    zh: '付款方式',
    ja: '支払い方法',
  },
  'checkout.cardEnding': {
    en: 'Card ending in',
    es: 'Tarjeta que termina en',
    fr: 'Carte se terminant par',
    de: 'Karte endet mit',
    it: 'Carta che termina con',
    pt: 'Cartão terminando em',
    zh: '卡号以',
    ja: 'で終わるカード',
  },
  'checkout.expires': {
    en: 'Expires:',
    es: 'Vence:',
    fr: 'Expire:',
    de: 'Läuft ab:',
    it: 'Scade:',
    pt: 'Expira:',
    zh: '到期：',
    ja: '有効期限：',
  },
  'checkout.placeOrder': {
    en: 'Place Your Order',
    es: 'Realizar tu pedido',
    fr: 'Passer votre commande',
    de: 'Bestellung aufgeben',
    it: 'Effettua il tuo ordine',
    pt: 'Fazer seu pedido',
    zh: '提交订单',
    ja: '注文を確定',
  },
  'checkout.orderSummary': {
    en: 'Order Summary',
    es: 'Resumen del pedido',
    fr: 'Résumé de la commande',
    de: 'Bestellübersicht',
    it: 'Riepilogo ordine',
    pt: 'Resumo do pedido',
    zh: '订单摘要',
    ja: '注文概要',
  },
  'checkout.shippingLabel': {
    en: 'Shipping:',
    es: 'Envío:',
    fr: 'Livraison:',
    de: 'Versand:',
    it: 'Spedizione:',
    pt: 'Envio:',
    zh: '配送：',
    ja: '配送：',
  },
  'checkout.tax': {
    en: 'Tax:',
    es: 'Impuesto:',
    fr: 'Taxe:',
    de: 'Steuer:',
    it: 'Tassa:',
    pt: 'Imposto:',
    zh: '税费：',
    ja: '税金：',
  },
  'checkout.total': {
    en: 'Total:',
    es: 'Total:',
    fr: 'Total:',
    de: 'Gesamt:',
    it: 'Totale:',
    pt: 'Total:',
    zh: '总计：',
    ja: '合計：',
  },
  'checkout.orderPlaced': {
    en: 'Order Placed!',
    es: '¡Pedido realizado!',
    fr: 'Commande passée!',
    de: 'Bestellung aufgegeben!',
    it: 'Ordine effettuato!',
    pt: 'Pedido realizado!',
    zh: '订单已提交！',
    ja: '注文が確定しました！',
  },
  'checkout.thankYou': {
    en: 'Thank you for your order. Your order confirmation number is:',
    es: 'Gracias por tu pedido. Tu número de confirmación de pedido es:',
    fr: 'Merci pour votre commande. Votre numéro de confirmation de commande est:',
    de: 'Vielen Dank für Ihre Bestellung. Ihre Bestellbestätigungsnummer lautet:',
    it: 'Grazie per il tuo ordine. Il tuo numero di conferma ordine è:',
    pt: 'Obrigado pelo seu pedido. Seu número de confirmação do pedido é:',
    zh: '感谢您的订单。您的订单确认号是：',
    ja: 'ご注文ありがとうございます。注文確認番号は：',
  },
  'checkout.confirmationEmail': {
    en: 'A confirmation email has been sent to your email address.',
    es: 'Se ha enviado un correo de confirmación a tu dirección de correo electrónico.',
    fr: 'Un e-mail de confirmation a été envoyé à votre adresse e-mail.',
    de: 'Eine Bestätigungs-E-Mail wurde an Ihre E-Mail-Adresse gesendet.',
    it: 'Un\'email di conferma è stata inviata al tuo indirizzo email.',
    pt: 'Um e-mail de confirmação foi enviado para o seu endereço de e-mail.',
    zh: '确认邮件已发送到您的电子邮件地址。',
    ja: '確認メールがメールアドレスに送信されました。',
  },
  // Common actions
  'common.continueShopping': {
    en: 'Continue Shopping',
    es: 'Continuar comprando',
    fr: 'Continuer les achats',
    de: 'Einkaufen fortsetzen',
    it: 'Continua lo shopping',
    pt: 'Continuar comprando',
    zh: '继续购物',
    ja: 'ショッピングを続ける',
  },
  'common.loading': {
    en: 'Loading...',
    es: 'Cargando...',
    fr: 'Chargement...',
    de: 'Laden...',
    it: 'Caricamento...',
    pt: 'Carregando...',
    zh: '加载中...',
    ja: '読み込み中...',
  },
  'common.priceIncludesShipping': {
    en: 'Price includes shipping',
    es: 'El precio incluye envío',
    fr: 'Le prix comprend la livraison',
    de: 'Preis inklusive Versand',
    it: 'Il prezzo include la spedizione',
    pt: 'O preço inclui frete',
    zh: '价格包含运费',
    ja: '価格に配送料が含まれています',
  },
  'common.and': {
    en: 'and',
    es: 'y',
    fr: 'et',
    de: 'und',
    it: 'e',
    pt: 'e',
    zh: '和',
    ja: 'と',
  },
  // Product Titles
  'product.1.title': {
    en: 'Trench Coat',
    es: 'Gabardina',
    fr: 'Trench',
    de: 'Trenchcoat',
    it: 'Trench',
    pt: 'Trench',
    zh: '风衣',
    ja: 'トレンチコート',
  },
  'product.2.title': {
    en: 'Luxury Makeup Palette',
    es: 'Paleta de Maquillaje de Lujo',
    fr: 'Palette de Maquillage de Luxe',
    de: 'Luxus-Make-up-Palette',
    it: 'Palette Trucco di Lusso',
    pt: 'Paleta de Maquiagem de Luxo',
    zh: '奢华彩妆盘',
    ja: '高級メイクパレット',
  },
  'product.3.title': {
    en: 'Boots',
    es: 'Botas',
    fr: 'Bottes',
    de: 'Stiefel',
    it: 'Stivali',
    pt: 'Botas',
    zh: '靴子',
    ja: 'ブーツ',
  },
  'product.4.title': {
    en: 'Handbag',
    es: 'Bolso',
    fr: 'Sac à main',
    de: 'Handtasche',
    it: 'Borsa',
    pt: 'Bolsa',
    zh: '手提包',
    ja: 'ハンドバッグ',
  },
  'product.5.title': {
    en: 'Skincare Set',
    es: 'Set de Cuidado de la Piel',
    fr: 'Set de Soins',
    de: 'Hautpflege-Set',
    it: 'Set Cura della Pelle',
    pt: 'Kit de Cuidados com a Pele',
    zh: '护肤套装',
    ja: 'スキンケアセット',
  },
  'product.6.title': {
    en: 'Lipstick Collection',
    es: 'Colección de Lápiz Labial',
    fr: 'Collection de Rouge à Lèvres',
    de: 'Lippenstift-Kollektion',
    it: 'Collezione Rossetti',
    pt: 'Coleção de Batom',
    zh: '口红系列',
    ja: 'リップスティックコレクション',
  },
  'product.7.title': {
    en: 'Perfume',
    es: 'Perfume',
    fr: 'Parfum',
    de: 'Parfüm',
    it: 'Profumo',
    pt: 'Perfume',
    zh: '香水',
    ja: '香水',
  },
  'product.8.title': {
    en: 'New Arrival Makeup',
    es: 'Maquillaje de Novedades',
    fr: 'Maquillage Nouveautés',
    de: 'Neue Make-up-Produkte',
    it: 'Trucco Novità',
    pt: 'Maquiagem Novidades',
    zh: '新品彩妆',
    ja: '新作メイク',
  },
  'product.9.title': {
    en: 'Leather Belt',
    es: 'Cinturón de Cuero',
    fr: 'Ceinture en Cuir',
    de: 'Ledergürtel',
    it: 'Cintura in Pelle',
    pt: 'Cinto de Couro',
    zh: '皮带',
    ja: 'レザーベルト',
  },
  'product.10.title': {
    en: 'Tote Bag',
    es: 'Bolso Tote',
    fr: 'Sac Tote',
    de: 'Tasche',
    it: 'Borsa Tote',
    pt: 'Bolsa Tote',
    zh: '托特包',
    ja: 'トートバッグ',
  },
  'product.11.title': {
    en: 'Designer Pants',
    es: 'Pantalones de Diseñador',
    fr: 'Pantalon de Créateur',
    de: 'Designer-Hose',
    it: 'Pantaloni Firmati',
    pt: 'Calças de Estilista',
    zh: '设计师长裤',
    ja: 'デザイナーパンツ',
  },
  'product.12.title': {
    en: 'Earrings',
    es: 'Aretes',
    fr: 'Boucles d\'Oreilles',
    de: 'Ohrringe',
    it: 'Orecchini',
    pt: 'Brincos',
    zh: '耳环',
    ja: 'イヤリング',
  },
  'product.13.title': {
    en: 'Laptop',
    es: 'Portátil',
    fr: 'Ordinateur Portable',
    de: 'Laptop',
    it: 'Laptop',
    pt: 'Notebook',
    zh: '笔记本电脑',
    ja: 'ノートパソコン',
  },
  'product.14.title': {
    en: 'Mechanical Keyboard',
    es: 'Teclado Mecánico',
    fr: 'Clavier Mécanique',
    de: 'Mechanische Tastatur',
    it: 'Tastiera Meccanica',
    pt: 'Teclado Mecânico',
    zh: '机械键盘',
    ja: 'メカニカルキーボード',
  },
  'product.15.title': {
    en: 'Wireless Mouse',
    es: 'Ratón Inalámbrico',
    fr: 'Souris Sans Fil',
    de: 'Funkmaus',
    it: 'Mouse Wireless',
    pt: 'Mouse Sem Fio',
    zh: '无线鼠标',
    ja: 'ワイヤレスマウス',
  },
  'product.16.title': {
    en: 'Monitor',
    es: 'Monitor',
    fr: 'Moniteur',
    de: 'Monitor',
    it: 'Monitor',
    pt: 'Monitor',
    zh: '显示器',
    ja: 'モニター',
  },
  'product.17.title': {
    en: 'Headphones',
    es: 'Auriculares',
    fr: 'Casque Audio',
    de: 'Kopfhörer',
    it: 'Cuffie',
    pt: 'Fones de Ouvido',
    zh: '耳机',
    ja: 'ヘッドフォン',
  },
  'product.18.title': {
    en: 'Webcam',
    es: 'Webcam',
    fr: 'Webcam',
    de: 'Webcam',
    it: 'Webcam',
    pt: 'Webcam',
    zh: '网络摄像头',
    ja: 'ウェブカメラ',
  },
  'product.19.title': {
    en: 'USB Flash Drive',
    es: 'Memoria USB',
    fr: 'Clé USB',
    de: 'USB-Stick',
    it: 'Chiavetta USB',
    pt: 'Pen Drive',
    zh: 'U盘',
    ja: 'USBメモリ',
  },
  'product.20.title': {
    en: 'Bestseller Book',
    es: 'Libro Bestseller',
    fr: 'Livre Bestseller',
    de: 'Bestseller-Buch',
    it: 'Libro Bestseller',
    pt: 'Livro Bestseller',
    zh: '畅销书',
    ja: 'ベストセラー本',
  },
  'product.21.title': {
    en: 'New Release Book',
    es: 'Libro de Novedades',
    fr: 'Livre Nouveauté',
    de: 'Neuerscheinung',
    it: 'Libro Novità',
    pt: 'Livro Lançamento',
    zh: '新书',
    ja: '新刊',
  },
  'product.22.title': {
    en: 'First Aid Kit',
    es: 'Botiquín de Primeros Auxilios',
    fr: 'Trousse de Premiers Secours',
    de: 'Erste-Hilfe-Set',
    it: 'Kit di Primo Soccorso',
    pt: 'Kit de Primeiros Socorros',
    zh: '急救包',
    ja: '救急キット',
  },
  'product.23.title': {
    en: 'Blood Pressure Monitor',
    es: 'Monitor de Presión Arterial',
    fr: 'Tensiomètre',
    de: 'Blutdruckmessgerät',
    it: 'Misuratore di Pressione',
    pt: 'Medidor de Pressão Arterial',
    zh: '血压计',
    ja: '血圧計',
  },
  'product.24.title': {
    en: 'Batteries',
    es: 'Pilas',
    fr: 'Piles',
    de: 'Batterien',
    it: 'Batterie',
    pt: 'Pilhas',
    zh: '电池',
    ja: '電池',
  },
  'product.25.title': {
    en: 'USB Cable',
    es: 'Cable USB',
    fr: 'Câble USB',
    de: 'USB-Kabel',
    it: 'Cavo USB',
    pt: 'Cabo USB',
    zh: 'USB线',
    ja: 'USBケーブル',
  },
  'product.26.title': {
    en: 'Smart Speaker',
    es: 'Altavoz Inteligente',
    fr: 'Haut-parleur Intelligent',
    de: 'Smart Speaker',
    it: 'Altoparlante Intelligente',
    pt: 'Alto-falante Inteligente',
    zh: '智能音箱',
    ja: 'スマートスピーカー',
  },
  'product.27.title': {
    en: 'Smart Light Bulb',
    es: 'Bombilla Inteligente',
    fr: 'Ampoule Intelligente',
    de: 'Smart Glühbirne',
    it: 'Lampadina Intelligente',
    pt: 'Lâmpada Inteligente',
    zh: '智能灯泡',
    ja: 'スマート電球',
  },
  'product.28.title': {
    en: 'Gift Card',
    es: 'Tarjeta Regalo',
    fr: 'Carte Cadeau',
    de: 'Geschenkkarte',
    it: 'Carta Regalo',
    pt: 'Cartão Presente',
    zh: '礼品卡',
    ja: 'ギフトカード',
  },
  'product.29.title': {
    en: 'Deal Headphones',
    es: 'Auriculares en Oferta',
    fr: 'Casque Audio en Promotion',
    de: 'Angebot Kopfhörer',
    it: 'Cuffie in Offerta',
    pt: 'Fones em Oferta',
    zh: '特价耳机',
    ja: 'お得なヘッドフォン',
  },
  'product.30.title': {
    en: 'Deal Makeup',
    es: 'Maquillaje en Oferta',
    fr: 'Maquillage en Promotion',
    de: 'Angebot Make-up',
    it: 'Trucco in Offerta',
    pt: 'Maquiagem em Oferta',
    zh: '特价彩妆',
    ja: 'お得なメイク',
  },
  // Product Descriptions
  'product.1.description': {
    en: 'A classic trench coat, perfect for all seasons. Made from high-quality, water-resistant fabric with a timeless design.',
    es: 'Una gabardina clásica, perfecta para todas las estaciones. Hecha de tela de alta calidad e impermeable con un diseño atemporal.',
    fr: 'Un trench classique, parfait pour toutes les saisons. Fabriqué en tissu de haute qualité et résistant à l\'eau avec un design intemporel.',
    de: 'Ein klassischer Trenchcoat, perfekt für alle Jahreszeiten. Hergestellt aus hochwertigem, wasserabweisendem Stoff mit zeitlosem Design.',
    it: 'Un trench classico, perfetto per tutte le stagioni. Realizzato in tessuto di alta qualità e resistente all\'acqua con un design senza tempo.',
    pt: 'Um trench clássico, perfeito para todas as estações. Feito de tecido de alta qualidade e resistente à água com design atemporal.',
    zh: '经典风衣，适合所有季节。采用高品质防水面料，设计经典。',
    ja: 'すべての季節に最適なクラシックなトレンチコート。高品質の防水素材で、時代を超えたデザイン。',
  },
  'product.2.description': {
    en: 'A luxurious makeup palette featuring a wide range of colors for eyes, cheeks, and lips. Perfect for creating any look.',
    es: 'Una paleta de maquillaje de lujo con una amplia gama de colores para ojos, mejillas y labios. Perfecta para crear cualquier look.',
    fr: 'Une palette de maquillage de luxe avec une large gamme de couleurs pour les yeux, les joues et les lèvres. Parfaite pour créer n\'importe quel look.',
    de: 'Eine luxuriöse Make-up-Palette mit einer breiten Farbpalette für Augen, Wangen und Lippen. Perfekt zum Erstellen jedes Looks.',
    it: 'Una palette trucco di lusso con una vasta gamma di colori per occhi, guance e labbra. Perfetta per creare qualsiasi look.',
    pt: 'Uma paleta de maquiagem de luxo com uma ampla gama de cores para olhos, bochechas e lábios. Perfeita para criar qualquer visual.',
    zh: '奢华彩妆盘，包含眼影、腮红和唇彩的丰富色彩。适合打造各种妆容。',
    ja: '目、頬、唇のための幅広い色合いを備えた高級メイクパレット。あらゆるルックを作成するのに最適。',
  },
  'product.3.description': {
    en: 'Stylish and comfortable boots made from premium leather. Perfect for both casual and formal occasions.',
    es: 'Botas elegantes y cómodas hechas de cuero premium. Perfectas para ocasiones casuales y formales.',
    fr: 'Bottes élégantes et confortables en cuir premium. Parfaites pour les occasions décontractées et formelles.',
    de: 'Stilvolle und bequeme Stiefel aus Premium-Leder. Perfekt für sowohl lässige als auch formelle Anlässe.',
    it: 'Stivali eleganti e comodi realizzati in pelle premium. Perfetti per occasioni casual e formali.',
    pt: 'Botas elegantes e confortáveis feitas de couro premium. Perfeitas para ocasiões casuais e formais.',
    zh: '时尚舒适的靴子，采用优质皮革制成。适合休闲和正式场合。',
    ja: 'プレミアムレザーで作られたスタイリッシュで快適なブーツ。カジュアルとフォーマルな場面の両方に最適。',
  },
  'product.4.description': {
    en: 'A beautiful handbag crafted from genuine leather with elegant hardware. Spacious interior with multiple compartments.',
    es: 'Un hermoso bolso hecho de cuero genuino con herrajes elegantes. Interior espacioso con múltiples compartimentos.',
    fr: 'Un magnifique sac à main en cuir véritable avec des accessoires élégants. Intérieur spacieux avec plusieurs compartiments.',
    de: 'Eine schöne Handtasche aus echtem Leder mit elegantem Beschlag. Geräumiges Innere mit mehreren Fächern.',
    it: 'Una bella borsa realizzata in vera pelle con finiture eleganti. Interno spazioso con più scomparti.',
    pt: 'Uma bela bolsa feita de couro genuíno com ferragens elegantes. Interior espaçoso com múltiplos compartimentos.',
    zh: '精美手提包，采用真皮制作，配优雅五金。内部宽敞，多个隔层。',
    ja: 'エレガントなハードウェアを備えた本革製の美しいハンドバッグ。複数のコンパートメントを備えた広々とした内部。',
  },
  // Categories
  'category.coatsJackets': {
    en: 'Coats & Jackets',
    es: 'Abrigos y Chaquetas',
    fr: 'Manteaux et Vestes',
    de: 'Mäntel & Jacken',
    it: 'Cappotti e Giacche',
    pt: 'Casacos e Jaquetas',
    zh: '外套和夹克',
    ja: 'コートとジャケット',
  },
  'category.beauty': {
    en: 'Beauty',
    es: 'Belleza',
    fr: 'Beauté',
    de: 'Schönheit',
    it: 'Bellezza',
    pt: 'Beleza',
    zh: '美容',
    ja: '美容',
  },
  'category.shoes': {
    en: 'Shoes',
    es: 'Zapatos',
    fr: 'Chaussures',
    de: 'Schuhe',
    it: 'Scarpe',
    pt: 'Sapatos',
    zh: '鞋子',
    ja: '靴',
  },
  'category.handbags': {
    en: 'Handbags',
    es: 'Bolsos',
    fr: 'Sacs à Main',
    de: 'Handtaschen',
    it: 'Borse',
    pt: 'Bolsas',
    zh: '手提包',
    ja: 'ハンドバッグ',
  },
  'category.skincare': {
    en: 'Skincare',
    es: 'Cuidado de la Piel',
    fr: 'Soins de la Peau',
    de: 'Hautpflege',
    it: 'Cura della Pelle',
    pt: 'Cuidados com a Pele',
    zh: '护肤',
    ja: 'スキンケア',
  },
  'category.makeup': {
    en: 'Makeup',
    es: 'Maquillaje',
    fr: 'Maquillage',
    de: 'Make-up',
    it: 'Trucco',
    pt: 'Maquiagem',
    zh: '彩妆',
    ja: 'メイク',
  },
  'category.fragrances': {
    en: 'Fragrances',
    es: 'Fragancias',
    fr: 'Parfums',
    de: 'Düfte',
    it: 'Profumi',
    pt: 'Perfumes',
    zh: '香水',
    ja: 'フレグランス',
  },
  'category.newArrivals': {
    en: 'New Arrivals',
    es: 'Novedades',
    fr: 'Nouveautés',
    de: 'Neuheiten',
    it: 'Novità',
    pt: 'Novidades',
    zh: '新品',
    ja: '新着',
  },
  'category.accessories': {
    en: 'Accessories',
    es: 'Accesorios',
    fr: 'Accessoires',
    de: 'Accessoires',
    it: 'Accessori',
    pt: 'Acessórios',
    zh: '配饰',
    ja: 'アクセサリー',
  },
  'category.bags': {
    en: 'Bags',
    es: 'Bolsas',
    fr: 'Sacs',
    de: 'Taschen',
    it: 'Borse',
    pt: 'Bolsas',
    zh: '包袋',
    ja: 'バッグ',
  },
  'category.clothing': {
    en: 'Clothing',
    es: 'Ropa',
    fr: 'Vêtements',
    de: 'Kleidung',
    it: 'Abbigliamento',
    pt: 'Roupas',
    zh: '服装',
    ja: '衣類',
  },
  'category.jewelry': {
    en: 'Jewelry',
    es: 'Joyería',
    fr: 'Bijoux',
    de: 'Schmuck',
    it: 'Gioielli',
    pt: 'Joias',
    zh: '珠宝',
    ja: 'ジュエリー',
  },
  'category.computers': {
    en: 'Computers',
    es: 'Computadoras',
    fr: 'Ordinateurs',
    de: 'Computer',
    it: 'Computer',
    pt: 'Computadores',
    zh: '电脑',
    ja: 'コンピューター',
  },
  'category.monitors': {
    en: 'Monitors',
    es: 'Monitores',
    fr: 'Moniteurs',
    de: 'Monitore',
    it: 'Monitor',
    pt: 'Monitores',
    zh: '显示器',
    ja: 'モニター',
  },
  'category.audio': {
    en: 'Audio',
    es: 'Audio',
    fr: 'Audio',
    de: 'Audio',
    it: 'Audio',
    pt: 'Áudio',
    zh: '音频',
    ja: 'オーディオ',
  },
  'category.storage': {
    en: 'Storage',
    es: 'Almacenamiento',
    fr: 'Stockage',
    de: 'Speicher',
    it: 'Archiviazione',
    pt: 'Armazenamento',
    zh: '存储',
    ja: 'ストレージ',
  },
  'category.books': {
    en: 'Books',
    es: 'Libros',
    fr: 'Livres',
    de: 'Bücher',
    it: 'Libri',
    pt: 'Livros',
    zh: '图书',
    ja: '本',
  },
  'category.medical': {
    en: 'Medical Care',
    es: 'Atención Médica',
    fr: 'Soins Médicaux',
    de: 'Medizinische Versorgung',
    it: 'Assistenza Medica',
    pt: 'Cuidados Médicos',
    zh: '医疗护理',
    ja: '医療ケア',
  },
  'category.electronics': {
    en: 'Electronics',
    es: 'Electrónica',
    fr: 'Électronique',
    de: 'Elektronik',
    it: 'Elettronica',
    pt: 'Eletrônicos',
    zh: '电子产品',
    ja: '電子機器',
  },
  'category.smartHome': {
    en: 'Smart Home',
    es: 'Hogar Inteligente',
    fr: 'Maison Connectée',
    de: 'Smart Home',
    it: 'Casa Intelligente',
    pt: 'Casa Inteligente',
    zh: '智能家居',
    ja: 'スマートホーム',
  },
  'category.giftCards': {
    en: 'Gift Cards',
    es: 'Tarjetas Regalo',
    fr: 'Cartes Cadeaux',
    de: 'Geschenkkarten',
    it: 'Carte Regalo',
    pt: 'Cartões Presente',
    zh: '礼品卡',
    ja: 'ギフトカード',
  },
  'category.deals': {
    en: 'Deals',
    es: 'Ofertas',
    fr: 'Offres',
    de: 'Angebote',
    it: 'Offerte',
    pt: 'Ofertas',
    zh: '特价',
    ja: 'お得情報',
  },
  // Homepage Product Sections
  'home.shopSaks': {
    en: 'Shop Saks on Amazon',
    es: 'Comprar Saks en Amazon',
    fr: 'Acheter Saks sur Amazon',
    de: 'Saks bei Amazon kaufen',
    it: 'Acquista Saks su Amazon',
    pt: 'Comprar Saks na Amazon',
    zh: '在亚马逊购买Saks',
    ja: 'AmazonでSaksを購入',
  },
  'home.winterBeauty': {
    en: 'Winter beauty routine refresh',
    es: 'Renueva tu rutina de belleza de invierno',
    fr: 'Rafraîchissez votre routine beauté hivernale',
    de: 'Auffrischung der Winter-Pflegeroutine',
    it: 'Rinnova la tua routine di bellezza invernale',
    pt: 'Renove sua rotina de beleza de inverno',
    zh: '冬季美容焕新',
    ja: '冬の美容ルーティンをリフレッシュ',
  },
  'home.shopLuxuryBeauty': {
    en: 'Shop all luxury beauty',
    es: 'Comprar toda la belleza de lujo',
    fr: 'Acheter toute la beauté de luxe',
    de: 'Alle Luxus-Kosmetik kaufen',
    it: 'Acquista tutta la bellezza di lusso',
    pt: 'Comprar toda beleza de luxo',
    zh: '购买所有奢华美容产品',
    ja: 'すべての高級美容を購入',
  },
  'home.luxuryStyles': {
    en: 'Up to 50% off luxury styles',
    es: 'Hasta 50% de descuento en estilos de lujo',
    fr: 'Jusqu\'à 50% de réduction sur les styles de luxe',
    de: 'Bis zu 50% Rabatt auf Luxus-Stile',
    it: 'Fino al 50% di sconto su stili di lusso',
    pt: 'Até 50% de desconto em estilos de luxo',
    zh: '奢华款式最高50%折扣',
    ja: '高級スタイル最大50%オフ',
  },
  'home.shopDesignerMarkdowns': {
    en: 'Shop designer markdowns',
    es: 'Comprar rebajas de diseñador',
    fr: 'Acheter les réductions de créateurs',
    de: 'Designer-Rabatte kaufen',
    it: 'Acquista sconti di designer',
    pt: 'Comprar descontos de estilistas',
    zh: '购买设计师折扣',
    ja: 'デザイナーの割引を購入',
  },
  // Footer
  'footer.getToKnowUs': {
    en: 'Get to Know Us',
    es: 'Conócenos',
    fr: 'À propos de nous',
    de: 'Lernen Sie uns kennen',
    it: 'Conoscici',
    pt: 'Conheça-nos',
    zh: '了解我们',
    ja: '私たちについて',
  },
  'footer.careers': {
    en: 'Careers',
    es: 'Carreras',
    fr: 'Carrières',
    de: 'Karriere',
    it: 'Carriere',
    pt: 'Carreiras',
    zh: '招聘',
    ja: '採用情報',
  },
  'footer.blog': {
    en: 'Blog',
    es: 'Blog',
    fr: 'Blog',
    de: 'Blog',
    it: 'Blog',
    pt: 'Blog',
    zh: '博客',
    ja: 'ブログ',
  },
  'footer.aboutAmazon': {
    en: 'About Amazon',
    es: 'Acerca de Amazon',
    fr: 'À propos d\'Amazon',
    de: 'Über Amazon',
    it: 'Informazioni su Amazon',
    pt: 'Sobre a Amazon',
    zh: '关于亚马逊',
    ja: 'Amazonについて',
  },
  'footer.investorRelations': {
    en: 'Investor Relations',
    es: 'Relaciones con Inversores',
    fr: 'Relations Investisseurs',
    de: 'Investor Relations',
    it: 'Relazioni con gli Investitori',
    pt: 'Relações com Investidores',
    zh: '投资者关系',
    ja: '投資家向け情報',
  },
  'footer.amazonDevices': {
    en: 'Amazon Devices',
    es: 'Dispositivos Amazon',
    fr: 'Appareils Amazon',
    de: 'Amazon-Geräte',
    it: 'Dispositivi Amazon',
    pt: 'Dispositivos Amazon',
    zh: '亚马逊设备',
    ja: 'Amazonデバイス',
  },
  'footer.makeMoneyWithUs': {
    en: 'Make Money with Us',
    es: 'Gana Dinero con Nosotros',
    fr: 'Gagnez de l\'Argent avec Nous',
    de: 'Verdienen Sie Geld mit uns',
    it: 'Guadagna con Noi',
    pt: 'Ganhe Dinheiro Conosco',
    zh: '和我们一起赚钱',
    ja: '私たちと一緒に稼ぐ',
  },
  'footer.sellProducts': {
    en: 'Sell products on Amazon',
    es: 'Vender productos en Amazon',
    fr: 'Vendre des produits sur Amazon',
    de: 'Produkte bei Amazon verkaufen',
    it: 'Vendi prodotti su Amazon',
    pt: 'Vender produtos na Amazon',
    zh: '在亚马逊销售产品',
    ja: 'Amazonで商品を販売',
  },
  'footer.sellBusiness': {
    en: 'Sell on Amazon Business',
    es: 'Vender en Amazon Business',
    fr: 'Vendre sur Amazon Business',
    de: 'Bei Amazon Business verkaufen',
    it: 'Vendi su Amazon Business',
    pt: 'Vender no Amazon Business',
    zh: '在Amazon Business销售',
    ja: 'Amazon Businessで販売',
  },
  'footer.sellApps': {
    en: 'Sell apps on Amazon',
    es: 'Vender aplicaciones en Amazon',
    fr: 'Vendre des applications sur Amazon',
    de: 'Apps bei Amazon verkaufen',
    it: 'Vendi app su Amazon',
    pt: 'Vender aplicativos na Amazon',
    zh: '在亚马逊销售应用',
    ja: 'Amazonでアプリを販売',
  },
  'footer.becomeAffiliate': {
    en: 'Become an Affiliate',
    es: 'Conviértete en Afiliado',
    fr: 'Devenir Partenaire',
    de: 'Partner werden',
    it: 'Diventa Partner',
    pt: 'Torne-se um Afiliado',
    zh: '成为联盟会员',
    ja: 'アフィリエイトになる',
  },
  'footer.advertiseProducts': {
    en: 'Advertise Your Products',
    es: 'Anuncia tus Productos',
    fr: 'Annoncez vos Produits',
    de: 'Bewerben Sie Ihre Produkte',
    it: 'Pubblica i tuoi Prodotti',
    pt: 'Anuncie seus Produtos',
    zh: '推广您的产品',
    ja: '商品を宣伝',
  },
  'footer.paymentProducts': {
    en: 'Amazon Payment Products',
    es: 'Productos de Pago de Amazon',
    fr: 'Produits de Paiement Amazon',
    de: 'Amazon-Zahlungsprodukte',
    it: 'Prodotti di Pagamento Amazon',
    pt: 'Produtos de Pagamento Amazon',
    zh: '亚马逊支付产品',
    ja: 'Amazon決済製品',
  },
  'footer.businessCard': {
    en: 'Amazon Business Card',
    es: 'Tarjeta Amazon Business',
    fr: 'Carte Amazon Business',
    de: 'Amazon Business-Karte',
    it: 'Carta Amazon Business',
    pt: 'Cartão Amazon Business',
    zh: 'Amazon Business卡',
    ja: 'Amazon Businessカード',
  },
  'footer.shopWithPoints': {
    en: 'Shop with Points',
    es: 'Comprar con Puntos',
    fr: 'Acheter avec des Points',
    de: 'Mit Punkten einkaufen',
    it: 'Acquista con Punti',
    pt: 'Comprar com Pontos',
    zh: '使用积分购物',
    ja: 'ポイントで購入',
  },
  'footer.reloadBalance': {
    en: 'Reload Your Balance',
    es: 'Recargar tu Saldo',
    fr: 'Recharger votre Solde',
    de: 'Guthaben aufladen',
    it: 'Ricarica il tuo Saldo',
    pt: 'Recarregar seu Saldo',
    zh: '充值余额',
    ja: '残高をチャージ',
  },
  'footer.currencyConverter': {
    en: 'Amazon Currency Converter',
    es: 'Conversor de Moneda de Amazon',
    fr: 'Convertisseur de Devises Amazon',
    de: 'Amazon-Währungsrechner',
    it: 'Convertitore di Valuta Amazon',
    pt: 'Conversor de Moeda Amazon',
    zh: '亚马逊货币转换器',
    ja: 'Amazon通貨コンバーター',
  },
  'footer.needHelp': {
    en: 'Need Help?',
    es: '¿Necesitas Ayuda?',
    fr: 'Besoin d\'Aide?',
    de: 'Benötigen Sie Hilfe?',
    it: 'Hai Bisogno di Aiuto?',
    pt: 'Precisa de Ajuda?',
    zh: '需要帮助？',
    ja: 'ヘルプが必要ですか？',
  },
  'footer.covid19': {
    en: 'COVID-19 and Amazon',
    es: 'COVID-19 y Amazon',
    fr: 'COVID-19 et Amazon',
    de: 'COVID-19 und Amazon',
    it: 'COVID-19 e Amazon',
    pt: 'COVID-19 e Amazon',
    zh: 'COVID-19和亚马逊',
    ja: 'COVID-19とAmazon',
  },
  'footer.yourAccount': {
    en: 'Your Account',
    es: 'Tu Cuenta',
    fr: 'Votre Compte',
    de: 'Ihr Konto',
    it: 'Il tuo Account',
    pt: 'Sua Conta',
    zh: '您的账户',
    ja: 'アカウント',
  },
  'footer.yourOrders': {
    en: 'Your Orders',
    es: 'Tus Pedidos',
    fr: 'Vos Commandes',
    de: 'Ihre Bestellungen',
    it: 'I tuoi Ordini',
    pt: 'Seus Pedidos',
    zh: '您的订单',
    ja: '注文履歴',
  },
  'footer.shippingRates': {
    en: 'Shipping Rates & Policies',
    es: 'Tarifas y Políticas de Envío',
    fr: 'Tarifs et Politiques d\'Expédition',
    de: 'Versandkosten & Richtlinien',
    it: 'Tariffe e Politiche di Spedizione',
    pt: 'Taxas e Políticas de Envio',
    zh: '配送费率和政策',
    ja: '配送料とポリシー',
  },
  'footer.returnsReplacements': {
    en: 'Returns & Replacements',
    es: 'Devoluciones y Reemplazos',
    fr: 'Retours et Remplacements',
    de: 'Rückgaben & Umtausch',
    it: 'Resi e Sostituzioni',
    pt: 'Devoluções e Trocas',
    zh: '退货和换货',
    ja: '返品と交換',
  },
  'footer.help': {
    en: 'Help',
    es: 'Ayuda',
    fr: 'Aide',
    de: 'Hilfe',
    it: 'Aiuto',
    pt: 'Ajuda',
    zh: '帮助',
    ja: 'ヘルプ',
  },
  'footer.conditionsOfUse': {
    en: 'Conditions of Use',
    es: 'Condiciones de Uso',
    fr: 'Conditions d\'Utilisation',
    de: 'Nutzungsbedingungen',
    it: 'Condizioni d\'Uso',
    pt: 'Condições de Uso',
    zh: '使用条件',
    ja: '利用規約',
  },
  'footer.privacyNotice': {
    en: 'Privacy Notice',
    es: 'Aviso de Privacidad',
    fr: 'Avis de Confidentialité',
    de: 'Datenschutzerklärung',
    it: 'Informativa sulla Privacy',
    pt: 'Aviso de Privacidade',
    zh: '隐私声明',
    ja: 'プライバシー規約',
  },
  'footer.adsPrivacyChoices': {
    en: 'Your Ads Privacy Choices',
    es: 'Opciones de Privacidad de Anuncios',
    fr: 'Choix de Confidentialité des Publicités',
    de: 'Ihre Datenschutzoptionen für Werbung',
    it: 'Scelte sulla Privacy degli Annunci',
    pt: 'Opções de Privacidade de Anúncios',
    zh: '您的广告隐私选择',
    ja: '広告のプライバシー設定',
  },
  'footer.copyright': {
    en: '© 1996-2024, Amazon.com, Inc. or its affiliates',
    es: '© 1996-2024, Amazon.com, Inc. o sus afiliados',
    fr: '© 1996-2024, Amazon.com, Inc. ou ses filiales',
    de: '© 1996-2024, Amazon.com, Inc. oder verbundene Unternehmen',
    it: '© 1996-2024, Amazon.com, Inc. o i suoi affiliati',
    pt: '© 1996-2024, Amazon.com, Inc. ou suas afiliadas',
    zh: '© 1996-2024, Amazon.com, Inc. 或其关联公司',
    ja: '© 1996-2024, Amazon.com, Inc. またはその関連会社',
  },
  // Info Pages
  'info.title': {
    en: 'Get to Know Us',
    es: 'Conócenos',
    fr: 'À propos de nous',
    de: 'Lernen Sie uns kennen',
    it: 'Conoscici',
    pt: 'Conheça-nos',
    zh: '了解我们',
    ja: '私たちについて',
  },
  'sell.title': {
    en: 'Make Money with Us',
    es: 'Gana Dinero con Nosotros',
    fr: 'Gagnez de l\'Argent avec Nous',
    de: 'Verdienen Sie Geld mit uns',
    it: 'Guadagna con Noi',
    pt: 'Ganhe Dinheiro Conosco',
    zh: '和我们一起赚钱',
    ja: '私たちと一緒に稼ぐ',
  },
  'payments.title': {
    en: 'Amazon Payment Products',
    es: 'Productos de Pago de Amazon',
    fr: 'Produits de Paiement Amazon',
    de: 'Amazon-Zahlungsprodukte',
    it: 'Prodotti di Pagamento Amazon',
    pt: 'Produtos de Pagamento Amazon',
    zh: '亚马逊支付产品',
    ja: 'Amazon決済製品',
  },
  'help.title': {
    en: 'Need Help?',
    es: '¿Necesitas Ayuda?',
    fr: 'Besoin d\'Aide?',
    de: 'Benötigen Sie Hilfe?',
    it: 'Hai Bisogno di Aiuto?',
    pt: 'Precisa de Ajuda?',
    zh: '需要帮助？',
    ja: 'ヘルプが必要ですか？',
  },
  'legal.conditions.title': {
    en: 'Conditions of Use',
    es: 'Condiciones de Uso',
    fr: 'Conditions d\'Utilisation',
    de: 'Nutzungsbedingungen',
    it: 'Condizioni d\'Uso',
    pt: 'Condizioni di Uso',
    zh: '使用条件',
    ja: '利用規約',
  },
  'legal.privacy.title': {
    en: 'Privacy Notice',
    es: 'Aviso de Privacidad',
    fr: 'Avis de Confidentialité',
    de: 'Datenschutzerklärung',
    it: 'Informativa sulla Privacy',
    pt: 'Aviso de Privacidade',
    zh: '隐私声明',
    ja: 'プライバシー規約',
  },
  'legal.adsPrivacy.title': {
    en: 'Your Ads Privacy Choices',
    es: 'Opciones de Privacidad de Anuncios',
    fr: 'Choix de Confidentialité des Publicités',
    de: 'Ihre Datenschutzoptionen für Werbung',
    it: 'Scelte sulla Privacy degli Annunci',
    pt: 'Opções de Privacidade de Anúncios',
    zh: '您的广告隐私选择',
    ja: '広告のプライバシー設定',
  },
  // Login page note
  'login.note': {
    en: 'Note: Create an account first if this doesn\'t work, or use the register page.',
    es: 'Nota: Crea una cuenta primero si esto no funciona, o usa la página de registro.',
    fr: 'Note: Créez d\'abord un compte si cela ne fonctionne pas, ou utilisez la page d\'inscription.',
    de: 'Hinweis: Erstellen Sie zuerst ein Konto, wenn dies nicht funktioniert, oder verwenden Sie die Registrierungsseite.',
    it: 'Nota: Crea prima un account se questo non funziona, o usa la pagina di registrazione.',
    pt: 'Nota: Crie uma conta primeiro se isso não funcionar, ou use a página de registro.',
    zh: '注意：如果这不起作用，请先创建账户，或使用注册页面。',
    ja: '注意：これが機能しない場合は、まずアカウントを作成するか、登録ページを使用してください。',
  },
  // Common labels
  'common.qty': {
    en: 'Qty:',
    es: 'Cant:',
    fr: 'Qté:',
    de: 'Menge:',
    it: 'Qtà:',
    pt: 'Qtd:',
    zh: '数量：',
    ja: '数量：',
  },
  'common.quantity': {
    en: 'Quantity:',
    es: 'Cantidad:',
    fr: 'Quantité:',
    de: 'Menge:',
    it: 'Quantità:',
    pt: 'Quantidade:',
    zh: '数量：',
    ja: '数量：',
  },
  'common.delivered': {
    en: 'Delivered',
    es: 'Entregado',
    fr: 'Livré',
    de: 'Geliefert',
    it: 'Consegnato',
    pt: 'Entregue',
    zh: '已送达',
    ja: '配達済み',
  },
  'common.productNotFound': {
    en: 'Product not found',
    es: 'Producto no encontrado',
    fr: 'Produit introuvable',
    de: 'Produkt nicht gefunden',
    it: 'Prodotto non trovato',
    pt: 'Produto não encontrado',
    zh: '未找到商品',
    ja: '商品が見つかりません',
  },
  // Hero Section
  'hero.watchAllSeason': {
    en: 'WATCH ALL SEASON',
    es: 'VER TODA LA TEMPORADA',
    fr: 'REGARDEZ TOUTE LA SAISON',
    de: 'GANZE SAISON ANSEHEN',
    it: 'GUARDA TUTTA LA STAGIONE',
    pt: 'ASSISTIR TODA A TEMPORADA',
    zh: '观看整个赛季',
    ja: 'シーズン全体を見る',
  },
  'hero.termsApply': {
    en: 'Terms apply.',
    es: 'Se aplican términos.',
    fr: 'Conditions applicables.',
    de: 'Bedingungen gelten.',
    it: 'Si applicano i termini.',
    pt: 'Termos se aplicam.',
    zh: '适用条款。',
    ja: '条件が適用されます。',
  },
  'hero.lakers': {
    en: 'Lakers',
    es: 'Lakers',
    fr: 'Lakers',
    de: 'Lakers',
    it: 'Lakers',
    pt: 'Lakers',
    zh: '湖人队',
    ja: 'レイカーズ',
  },
  'hero.spurs': {
    en: 'Spurs',
    es: 'Spurs',
    fr: 'Spurs',
    de: 'Spurs',
    it: 'Spurs',
    pt: 'Spurs',
    zh: '马刺队',
    ja: 'スパーズ',
  },
  'hero.pistons': {
    en: 'Pistons',
    es: 'Pistons',
    fr: 'Pistons',
    de: 'Pistons',
    it: 'Pistons',
    pt: 'Pistons',
    zh: '活塞队',
    ja: 'ピストンズ',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  currentLanguage: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('amazon-language') as Language;
    if (savedLanguage && languages.find(l => l.code === savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // Save language to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem('amazon-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[key]?.[language] || translations[key]?.['en'] || key;
  };

  const currentLanguage = languages.find(l => l.code === language) || languages[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

